version: '3'
services:
#  nginx:
#    container_name: myweb-proxy
#    image: nginx:1.21.5-alpine
#    ports:
#      - 80:80
#    volumes:
#      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - login-api
#      - admin-api
#      - customer-api
#      - restaurant-api
#      - admin-web
#      - customer-web
#      - restaurant-web
  mysql:
    image: mariadb:10.4.7
    env_file: .env
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 13306:3306
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD",  "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  login-api:
    container_name: login-api
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/eatgo/run.sh
      - ./eatgo-login-api/build/libs:/home/eatgo/libs
    ports:
      - 8001:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
    command: bash -c "cd /home/eatgo && sh run.sh"
  admin-api:
    container_name: admin-api
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/eatgo/run.sh
      - ./eatgo-admin-api/build/libs:/home/eatgo/libs
    ports:
      - 8002:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
    command: bash -c "cd /home/eatgo && sh run.sh"
  customer-api:
    container_name: customer-api
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/eatgo/run.sh
      - ./eatgo-customer-api/build/libs:/home/eatgo/libs
    ports:
      - 8003:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
    command: bash -c "cd /home/eatgo && sh run.sh"
  restaurant-api:
    container_name: restaurant-api
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/eatgo/run.sh
      - ./eatgo-restaurant-api/build/libs:/home/eatgo/libs
    ports:
      - 8004:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
    command: bash -c "cd /home/eatgo && sh run.sh"
  admin-web:
    container_name: admin-web
    image: node:10.16.3
    volumes:
      - ./eatgo-admin-web:/home/eatgo
    ports:
      - 8082:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - VUE_APP_API_BASE_URL=http://chit-chat.codeend.site:8002
      - VUE_APP_LOGIN_API_BASE_URL=http://chit-chat.codeend.site:8001
    command: bash -c "cd /home/eatgo && npm run serve"
    healthcheck:
      test: curl -sS http://localhost:8080 || exit 1
      timeout: 10s
      retries: 10
  customer-web:
    container_name: customer-web
    image: node:10.16.3
    volumes:
      - ./eatgo-customer-web:/home/eatgo
    ports:
      - 8083:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - VUE_APP_API_BASE_URL=http://chit-chat.codeend.site:8003
      - VUE_APP_LOGIN_API_BASE_URL=http://chit-chat.codeend.site:8001
    command: bash -c "cd /home/eatgo && npm run serve"
    healthcheck:
      test: curl -sS http://localhost:8080 || exit 1
      timeout: 10s
      retries: 10
  restaurant-web:
    container_name: restaurant-web
    image: node:10.16.3
    volumes:
      - ./eatgo-restaurant-web:/home/eatgo
    ports:
      - 8084:3000
    environment:
      - VUE_APP_API_BASE_URL=http://chit-chat.codeend.site:8004
      - VUE_APP_LOGIN_API_BASE_URL=http://chit-chat.codeend.site:8001
    command: bash -c "cd /home/eatgo && npm run serve"
    healthcheck:
      test: curl -sS http://localhost:8080 || exit 1
      timeout: 10s
      retries: 10
